### ISSUE TITLE
Incorrect variable used in SyncLounge example

### ISSUE THREAD

**Issue by CLHatch** [GhostWriters/DockSTARTer.com#97]
I wasn't sure if you did pull requests on the docs, so figured I'd just point this out in an issue.

In the SyncLounge documentation, I believe the wrong variable is used in the "Override Servers List" example.

The example shows:
`version: "3.4" # this must match the version in docker-compose.yml
services:
  synclounge:
    volumes:
        - ${DOCKERSHAREDDIR}/synclounge/servers.json:/defaults/servers.json`

I would think that would actually be:
`version: "3.4" # this must match the version in docker-compose.yml
services:
  synclounge:
    volumes:
        - ${DOCKERCONFDIR}/synclounge/servers.json:/defaults/servers.json`

**Comment by nemchik** [comment]
I think you are correct, and yes we gladly accept PRs to the docs. There's even an edit button at the top right of every page on the docs site. If you'd like to make a PR I'll get it merged.

**Comment by MagicalCodeMonkey** [comment]
Thanks for reporting this! It has been change and should be updated on the site shortly.
